version: "3.7"

# 定义services
services:
  api:
    image: hujiande/alpine:1.1.0
    network_mode: host
    volumes:
      - .:/app
    logging: 
        driver: json-file
        options:
          max-size: "200k"
          max-file: "10"
    environment:
      - LOG_V=3
      - LOG_STDOUT=false
      - LOG_DIR=./runtime/log
    entrypoint: "./api -conf configs"