version: "3.7"

# 定义services
services:
  api:
    image: hujiande/alpine:1.1.0
    network_mode: host
    volumes:
      - .:/app
      - ../glibs:/glibs
    logging: 
        driver: json-file
        options:
          max-size: "200k"
          max-file: "10"
    entrypoint:
      - ./api